apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-labs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-labs
  template:
    metadata:
      labels:
        app: cloud-labs
    spec:
      containers:
        - name: cloud
          image: docker.io/library/cloud
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: env-secret
